services:
  server:
    build:
      context: .
      target: development
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD_FILE: /run/secrets/db-password
      ACCEPT_EULA: "Y"
      MSSQL_DB: example
    secrets:
      - db-password
    volumes:
      - db-data:/var/opt/mssql
    expose:
      - 1433
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P $(cat /run/secrets/db-password) -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
