name: Build .NET WebApp
on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "**.cs"
      - "**.csproj"
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
env:
  DOTNET_VERSION: "8.0.x"
  ROOT_PATH: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ${{env.ROOT_PATH}}

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: ${{env.ROOT_PATH}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
