name: Build .NET WebApp
on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "**.cs"
      - "**.csproj"
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
env:
  DOTNET_VERSION: "8.0.x"
  ROOT_PATH: ./src

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    environment: production
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Set DOTNET_ROOT for Windows

        if: runner.os == 'Windows'
        run: echo "DOTNET_ROOT=C:\Program Files\dotnet" >> $GITHUB_ENV

      - name: Set DOTNET_ROOT for MacOS
        if: runner.os == 'macOS'
        run: echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV

      - name: Install/Restore dependencies
        run: dotnet restore src.csproj
        working-directory: ${{ env.ROOT_PATH }}

      - name: Build
        run: dotnet build src.csproj --configuration Release --no-restore
        working-directory: ${{env.ROOT_PATH}}

      - name: Test with the dotnet CLI
        run: dotnet test src.csproj --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
        working-directory: ${{env.ROOT_PATH}}

      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ${{ env.ROOT_PATH }}

      - name: Upload dotnet test artifact results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
