name: Build .NET WebApp
on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "**.cs"
      - "**.csproj"
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore ./src/src.csproj
    - name: Build
      run: dotnet build ./src/src.csproj --configuration Release --no-restore
    - name: Test with the dotnet CLI
      run: dotnet test ./src/src.csproj --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
      if: ${{ always() }}
